version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.2
    steps:
      - checkout
      - run: npm i
      - run: npm test
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD